### ISSUE TITLE
Handle the conversion of elliptic tori

### ISSUE THREAD

**Issue by arekfu** [arekfu/t4_geom_convert#3]
Only circular tori are handled for the moment.

**Comment by arekfu** [comment]
OK, correction: elliptic tori are converted fine if no transformation is applied. When a transformation is applied, `mip` chokes on the torus with the following error:
```
Traceback (most recent call last):
[...]                                                                                                                                                                                                           
  File "/.../t4_geom_convert/t4_geom_convert/MIP/geom/forcad.py", line 397, in tz
    x, y, z, r1, r2 = _check_torus(p)
  File "/.../t4_geom_convert/t4_geom_convert/MIP/geom/forcad.py", line 373, in _check_torus
    raise NotImplementedError('Cannot convert torus with B != C')
NotImplementedError: Cannot convert torus with B != C
```
